FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    python3-tk \
    xvfb \
    x11-apps \
    && pip install pybullet \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY brazo.py .

CMD ["python", "brazo.py"]
